/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->result_value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->code))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_1_argument (XDR *xdrs, suma_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplica_1_argument (XDR *xdrs, multiplica_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_divide_1_argument (XDR *xdrs, divide_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}
